### ISSUE TITLE
option for specify the endpoint ip address and port

### ISSUE THREAD

**Issue by chronicom** [complexorganizations/wireguard-manager#168]
Hi, thank you for the great work.

In our setup, the wireguard is running on a server without public IP. I setup port forwarding on the router to forward the connection to the wireguard server. At this moment when I add a new peer,  the endpoint in the configuration file is always []:51820.  I would like to  explicitly specify or pre-configure the public IP and port when I add a new peer. I dont seem to find an option from the script. Is it possible to add this option?

Many thanks.

**Comment by Prajwal-Koirala** [comment]
Hey,
Thank you for your bug report, and the bug has been fixed in upstream so other users will never have this issue ever.
https://github.com/complexorganizations/wireguard-manager/commit/2eff6ae8c7d73fd5a801a2747a393d68157ca3cb
To fix this issue, please open `/etc/wireguard/wg0.conf` and than go on line one and replace `[]` to your public ip.
sorry for the issue your facing but its been fixed now.

**Comment by chronicom** [comment]
thank you very much I will try it out

**Comment by Prajwal-Koirala** [comment]
@chronicom 
Merged with main.
