### ISSUE TITLE
Issue with Adding New Peer: IP Address Already in Use by WireGuard

### ISSUE THREAD

**Issue by WoozyFace** [complexorganizations/wireguard-manager#454]
Nothhing here.

**Comment by itatelier** [comment]
Confirm same issue

**Comment by ShaAlexander** [comment]
I have deleted this software and will not use it again. Unfortunately, this program corrupted my entire VPN server setup file. I strongly recommend using PiVPN instead, as it is much more reliable and efficient.

To the developer: If you plan to share software, ensure it works properly and does not risk corrupting critical files. This experience has caused significant issues, and I hope future updates address these problems.

**Comment by Rebelllious** [comment]
@ShaAlexander I am not the developer, but would still ask you to clarify a few points: 
1. Did you perform initial Wireguard installation and configuration using this script? Or did you just try to add a new peer to an already existing installation done with the help of some other workflow? 
2. From what I remember, this script comes with no guarantee, either expressed or implied, that it will work for your specific scenario. Hence, it would be a good idea to first test it and then run it against anything that is critical for you. 

And one more thing - I did invest a bit of time into making this script work for RHEL-compatible distros, but have not been involved recently as the author himself seems to have lost interest in this project.

**Comment by ShaAlexander** [comment]
> @ShaAlexander I am not the developer, but would still ask you to clarify a few points:
> 
> 1. Did you perform initial Wireguard installation and configuration using this script? Or did you just try to add a new peer to an already existing installation done with the help of some other workflow?

First I had a manual setup I removed and purged that.  so first option.

> 2. From what I remember, this script comes with no guarantee, either expressed or implied, that it will work for your specific scenario. Hence, it would be a good idea to first test it and then run it against anything that is critical for you.
> 
If you have time to test, not if due to a broken Internet cable below the streets outside. and every website and web app is down. 

> And one more thing - I did invest a bit of time into making this script work for RHEL-compatible distros, but have not been involved recently as the author himself seems to have lost interest in this project.

Maybe he had a reason to loose intrest, since PIVPN is even newer and yet a better script. The one of the old dev contains a lot of outdated spaghetti code..

**Comment by Rebelllious** [comment]
PiVPN has one big downside - it only works on Ubuntu / Debian systems. No Fedora / Rocky / Alma / Oracle Linux support.

**Comment by ShaAlexander** [comment]
> PiVPN has one big downside - it only works on Ubuntu / Debian systems. No Fedora / Rocky / Alma / Oracle Linux support.

**I closed this topic for a reason. Do you really have a valid justification for reopening it? Because so far, all you've shown is a complete lack of understanding of what you're doing.**

Really? This is the level of your understanding? First of all, this might be a user-specific issue. Connecting to a VPN doesn't depend on the software you're using—it makes no difference. Oh, and since it's Linux, compile it for your specific distro if needed. Simple as that."

explanation

User-Specific Issue: It's possible the problem is specific to the user's setup, but this depends on the context of the issue. Factors like configuration, permissions, or compatibility can vary between users.

Connecting to a VPN on Any Software: While connecting to a VPN generally follows standard protocols (e.g., OpenVPN, WireGuard, etc.), the method can vary based on the software or platform. For example, different operating systems and software tools have their own ways of handling VPN connections.

Linux and Compilation: It’s true that some software on Linux may require compiling for specific distributions, especially if it's not available as a pre-compiled package in the distro's repositories. However, many VPN solutions (like OpenVPN or WireGuard) are widely available as pre-compiled packages for most Linux distributions, making manual compilation unnecessary for most users. 


Goodbye. Do not reply or reopen this topic. So rude... sigh. you can answer again if you have learned the basics of Linux... So stop wasting my time with nonsense bullshit answers.

**Comment by itatelier** [comment]
> PiVPN

 [v4.6.0: The end](https://github.com/pivpn/pivpn/releases/tag/v4.6.0)

**Comment by itatelier** [comment]
> 1. you just try to add a new peer to an already existing installation

in my case i just try to add a new peer to an already existing installation. With clear from peers wg config all works good!

**Comment by Rebelllious** [comment]
@ShaAlexander the only person showing incompetence and lack of understanding here is you. If you are that smart and advanced in Linux (which you might still be, who knows), you could have checked the code of PiVPN and found out that it can only configure a VPN server on Ubuntu and Debian (and Alpine, if I am not mistaken, but that one is not a major player). And this is exactly what I mentioned in the previous reply. I am not talking about clients, we are here for VPN server.
Cheers.
And be nice to people next time you are online, please.

**Comment by ShaAlexander** [comment]
"It's clear that you did not create this software yourself. In fact, everything you present is just a derivative of others' work. Your criticism of Debian and Ubuntu is unfounded; these distributions are widely used in the server world for a reason. Their popularity stems from their compatibility and robust capabilities.

I usually strive to be polite, but if I've made it clear that a topic is closed, I expect that to be respected. Your attitude comes across as arrogant and know-it-all, even though you've admitted that you didn't create what you're criticizing. Do you think you're infallible? If so, I suggest taking a step back and reconsidering your approach.

SO F*** OFF and never try to come into my life again. Get some cancer and die or something, f***ing retard. Maybe you should ask your mom to do an abortion with retroactive force. 

I WIS YOU THE WORST THINGS IN LIVE AND HOPE YOU WILL SUFFER!

**Comment by ShaAlexander** [comment]
DUDE JUST FUCK OFF GO AWAY I DONT CARE ABOUT YOU, Please go die or something so I can raise a dance party on top of your grave. And next time, just  remember how you got bullied so much, actually tat time you wanted to die you should had committed suicide or your parrents how abused you had a better life, everyone in fact. Told by themselves back in the day.

**Comment by WoozyFace** [comment]
If you respected the fact that I closed this topic and didn’t feel the need to have the last word like some know-it-all, then maybe I could act nice to you. But nope, I don’t give a shit about how you feel treated or about you. If you were smart, you’d let someone else handle the important tasks of life, and you could do the basic ones. Jump from a height or in front of... I don't care. Don’t get in my life ever again.

**Comment by WoozyFace** [comment]
This plugin is making everything corrupt. Maybe if I hadn't caught that in time, it would not only have broken itself, but also the rest of my server files. It's like a WannaCry script, only this developer didn't even..
